### PR TITLE
fix: make sure we instantiate non-main modules

### LINKED ISSUE #92: Broken module instantiation
On the latest main branch (bef00f3) only main WASM module gets instantiated and all other modules are only compiled, but not instantiated.

In release version v1.6.1 there is `c.Wazero.InstantiateWithConfig(ctx, data.Data, moduleConfig.WithName(data.Name))` which instantiates modules with a specified name, but in the main branch there is no instantiation of other modules, only compilation. 

Simplest example to reproduce is https://github.com/mhmd-azeez/extism_link_modules, with v1.6.1 works as expected, but on latest main it fails with the error:
```
Failed to initialize plugin: instantiating module: module[lib] not instantiated
```

### PR DESCRIPTION
**Pull request by mhmd-azeez**
Fixes #92

### CODE REVIEW

File: plugin.go
Comment (mymmrac) [inline plugin.go:1]: There is also a line:
```go
moduleConfig = moduleConfig.WithName(strconv.Itoa(int(p.instanceCount.Add(1))))
```
It seems to be redundant now + `p.instanceCount` also can be removed

File: plugin.go [hunk 1]
```diff
@@ -158,19 +162,18 @@ func NewCompiledPlugin(
...
 
-	modules := map[string]wazero.CompiledModule{}
 	for i, wasm := range manifest.Wasm {
 		data, err := wasm.ToWasmData(ctx)
 		if err != nil {
 			return nil, err
 		}
 
-		_, mainExists := modules["main"]
+		_, mainExists := p.modules["main"]
```
Comment (mymmrac) [inline plugin.go:171]: `mainExists` will always be `false` since we never add `main` module to the map

File: plugin.go [hunk 2]
```diff
@@ -266,6 +267,20 @@ func (p *CompiledPlugin) Instance(ctx context.Context, config PluginInstanceConf
 	}
 	closers = append(closers, extism.Close)
 
+	// Instantiate all non-main modules first
+	instancedModules := make(map[string]api.Module)
+	for name, module := range p.modules {
+		instance, err := p.runtime.InstantiateModule(ctx, module, moduleConfig.WithName(name))
+		if err != nil {
+			for _, m := range instancedModules {
```
Comment (mymmrac) [inline plugin.go:275]: What do you think about reusing `closers` here instead? If an error occurs, it will close all modules (`p.extism` too), also same thing can be added if error occurs when instantiating `main`, we will need to close other modules there too

**Review by mymmrac — CHANGES_REQUESTED** [review]

File: plugin.go
Comment (mhmd-azeez) [reply plugin.go:1]: hmmm, i am not sure, the comment for `p.instanceCount` suggests otherwise. @evacchi what do you think? I moved the naming closer to the main module initialization to make it clearer that this naming is for the main module

File: plugin.go (hunk 1 above)
Comment (mhmd-azeez) [reply plugin.go]: great catch!

File: plugin.go (hunk 2 above)
Comment (mhmd-azeez) [reply plugin.go]: good idea!

**Comment by mhmd-azeez** [comment]
@mymmrac thank you very much for the review!

File: plugin.go [hunk 3]
```diff
@@ -158,19 +162,18 @@ func NewCompiledPlugin(
...
-		_, mainExists := modules["main"]
-		if data.Name == "" || i == len(manifest.Wasm)-1 && !mainExists {
+		if data.Name == "" || i == len(manifest.Wasm)-1 && !foundMain {
 			data.Name = "main"
 		}
 
-		_, okm := modules[data.Name]
+		_, okm := p.modules[data.Name]
 
 		if data.Name == "extism:host/env" || okm {
```
Comment (mymmrac) [inline plugin.go:178]: There can be a case, when there are 2 modules with empty name, so both will become `main` which is an error
```suggestion
		if data.Name == "extism:host/env" || okm || (foundMain && data.Name == "main") {
```

Also, I think there should be a check that each module has non-empty name

File: plugin.go
Comment (mymmrac) [reply plugin.go:1]: Hmm, you are correct, `InstantiateModule` comment states that module name can't be reused, this probably also means that other modules can't be instantiated multiple times?

Comment (evacchi) [reply plugin.go:1]: IIRC not with the same name, within the same runtime

**Comment by mhmd-azeez** [comment]
@mymmrac i found a way to make module linking work with multiple modules by wrapping the non-main modules in a host module. Can you please test this and see if it works with your use case too?

**Review by evacchi — APPROVED** [review]
holy moly that's actually quite clever 😅 I wonder if there is a perf hit and/or we should allow to opt-in this behavior, but in general it seems like a cool workaround :D

**Comment by mhmd-azeez** [comment]
@evacchi good point, i will try to run a benchmark on sunday. I was also thinking maybe we implement both? and do one or the other depending if it's necessary. For example, if the user only needs one instance or if they only have one module, we don't need to do any of this (which is probably 90+% of the cases). So if there is a perf hit, we certainly can consider that too

**Comment by evacchi** [comment]
yeah that makes sense, we could just make it a flag

**Review by mymmrac — APPROVED** [review]
LGTM! Very clever solution, it adds a little bit of overhead when calling linked modules, but since it's not very common to have many modules (at list I think so) this is good for our case

**Review by evacchi — COMMENTED** [review]
I think the issue with Big Go is that we are really only initializing the main module, dependency are still not being initialized 🤔

File: runtime.go [hunk 4]
```diff
@@ -21,13 +22,13 @@ type guestRuntime struct {
 	initialized bool
 }
 
-func detectGuestRuntime(ctx context.Context, p *Plugin) guestRuntime {
-	runtime, ok := haskellRuntime(ctx, p, p.module)
+func detectGuestRuntime(p *Plugin) guestRuntime {
+	runtime, ok := haskellRuntime(p, p.mainModule)
```
Comment (evacchi) [inline runtime.go:26]: I think the issue with Big Go is that we are really only initializing the main module, dependency are still not being initialized 🤔

Comment (evacchi) [reply runtime.go:26]: (working on a patch...)

Comment (evacchi) [reply runtime.go]: @mhmd-azeez I pushed a commit to this branch (feel free to revert or iterate if you think it's appropriate) with a fix. The issue that I can foresee is that, if there are cross-dependencies between modules, then the init order is random! The "proper" way to init dependencies would be to linearize the dependency graph and then initialize it in that order. We can do that in a follow-up, though!

**Review by mymmrac — APPROVED** [review]
Fix for modules compiled with Go 1.24 works, thanks

File: runtime.go (hunk 4 above)
Comment (mhmd-azeez) [reply runtime.go]: thansk!

**Comment by mhmd-azeez** [comment]
The benchmarks don't show a significant difference for the normal case, so I am going to merge the PR and we can schedule any additional work in a new PR


main:
```
PS D:\dylibso\go-sdk> go.exe test -benchmem -run=^$ -bench ^BenchmarkInitialize$ github.com/extism/go-sdk
goos: windows
goarch: amd64
pkg: github.com/extism/go-sdk
cpu: 13th Gen Intel(R) Core(TM) i7-1365U
BenchmarkInitialize/noop-12                  100          11520235 ns/op         4583576 B/op       7138 allocs/op
PASS
ok      github.com/extism/go-sdk        1.297s
PS D:\dylibso\go-sdk> go.exe test -benchmem -run=^$ -bench ^BenchmarkInitialize$ github.com/extism/go-sdk
goos: windows
goarch: amd64
pkg: github.com/extism/go-sdk
cpu: 13th Gen Intel(R) Core(TM) i7-1365U
BenchmarkInitialize/noop-12                  124          10724696 ns/op         4583436 B/op       7140 allocs/op
PASS
ok      github.com/extism/go-sdk        2.428s
PS D:\dylibso\go-sdk> go.exe test -benchmem -run=^$ -bench ^BenchmarkInitialize$ github.com/extism/go-sdk
goos: windows
goarch: amd64
pkg: github.com/extism/go-sdk
cpu: 13th Gen Intel(R) Core(TM) i7-1365U
BenchmarkInitialize/noop-12                  129           9306463 ns/op         4583531 B/op       7141 allocs/op
PASS
ok      github.com/extism/go-sdk        2.286s
PS D:\dylibso\go-sdk>
```

`fix_module_linking`:
```
PS D:\dylibso\go-sdk> go test ./... -bench=.
ok      github.com/extism/go-sdk        66.679s
PS D:\dylibso\go-sdk> go.exe test -benchmem -run=^$ -bench ^BenchmarkInitialize$ github.com/extism/go-sdk
goos: windows
goarch: amd64
pkg: github.com/extism/go-sdk
cpu: 13th Gen Intel(R) Core(TM) i7-1365U
BenchmarkInitialize/noop-12                  126           9446520 ns/op         4583583 B/op       7143 allocs/op
PASS
ok      github.com/extism/go-sdk        2.258s
PS D:\dylibso\go-sdk> go.exe test -benchmem -run=^$ -bench ^BenchmarkInitialize$ github.com/extism/go-sdk
goos: windows
goarch: amd64
pkg: github.com/extism/go-sdk
cpu: 13th Gen Intel(R) Core(TM) i7-1365U
BenchmarkInitialize/noop-12                  124           9230943 ns/op         4583848 B/op       7148 allocs/op
PASS
ok      github.com/extism/go-sdk        2.262s
PS D:\dylibso\go-sdk> go.exe test -benchmem -run=^$ -bench ^BenchmarkInitialize$ github.com/extism/go-sdk
goos: windows
goarch: amd64
pkg: github.com/extism/go-sdk
cpu: 13th Gen Intel(R) Core(TM) i7-1365U
BenchmarkInitialize/noop-12                  100          12527209 ns/op         4583866 B/op       7144 allocs/op
PASS
ok      github.com/extism/go-sdk        1.408s
```
